// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class CSVFileConverter : MonoBehaviour
{
	int index;
	float maxTime;
	public static string myQuestion;
	public static string myAnswer;
	public static float quizTime;

	public QuizManager Manager;

    public void StartQuiz()
    {
		index = Random.Range(Manager.levelling.LevelValue * 10 - 9, Manager.levelling.LevelValue * 10);

		if (Levelling.Easy == true)
		{
			quizTime = Find_Index(index.ToString()).TimeEasy;
		}
		else if (Levelling.Medium == true)
		{
			quizTime = Find_Index(index.ToString()).TimeMedium;
		}
		else if (Levelling.Hard == true)
		{
			quizTime = Find_Index(index.ToString()).TimeHard;
		}

		//quizTime = (quizTime-10.0f) * 0.1f;
		Manager.TimeBar.maxValue = maxTime = quizTime;

		HasilBelajarManager.Row soal = Find_Index(index.ToString());
		myQuestion = soal.Soal;
		myAnswer = soal.Jawaban;

		Manager.timeManager.SetQuizTimer();
	}

	public List<HasilBelajarManager.Row> rowList()
	{
		return HasilBelajarManager.Instance.rowList;
	}

	public int NumRows()
	{
		return rowList().Count;
	}

	public HasilBelajarManager.Row GetAt(int i)
	{
		if (rowList().Count <= i)
			return null;
		return rowList()[i];
	}

	public HasilBelajarManager.Row Find_Level(string find)
	{
		return rowList().Find(x => x.Level == find);
	}
	public List<HasilBelajarManager.Row> FindAll_Level(string find)
	{
		return rowList().FindAll(x => x.Level == find);
	}
	public HasilBelajarManager.Row Find_Index(string find)
	{
		return rowList().Find(x => x.Index == find);
	}
	public List<HasilBelajarManager.Row> FindAll_Index(string find)
	{
		return rowList().FindAll(x => x.Index == find);
	}
	public HasilBelajarManager.Row Find_Soal(string find)
	{
		return rowList().Find(x => x.Soal == find);
	}
	public List<HasilBelajarManager.Row> FindAll_Soal(string find)
	{
		return rowList().FindAll(x => x.Soal == find);
	}
	public HasilBelajarManager.Row Find_Jawaban(string find)
	{
		return rowList().Find(x => x.Jawaban == find);
	}
	public List<HasilBelajarManager.Row> FindAll_Jawaban(string find)
	{
		return rowList().FindAll(x => x.Jawaban == find);
	}
	/*public HasilBelajarManager.Row Find_TimeEasy(string find)
	{
		return rowList().Find(x => x.TimeEasy == find);
	}
	public List<HasilBelajarManager.Row> FindAll_TimeEasy(string find)
	{
		return rowList().FindAll(x => x.TimeEasy == find);
	}
	public HasilBelajarManager.Row Find_TimeMedium(string find)
	{
		return rowList().Find(x => x.TimeMedium == find);
	}
	public List<HasilBelajarManager.Row> FindAll_TimeMedium(string find)
	{
		return rowList().FindAll(x => x.TimeMedium == find);
	}
	public HasilBelajarManager.Row Find_TimeHard(string find)
	{
		return rowList().Find(x => x.TimeHard == find);
	}
	public List<HasilBelajarManager.Row> FindAll_TimeHard(string find)
	{
		return rowList().FindAll(x => x.TimeHard == find);
	}*/

}